# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - '**' # matches every branch
  pull_request:
    branches: [ production ]

jobs:
  Package_and_Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        TREECREATE_JDBC_URL: ${{ secrets.TREECREATE_JDBC_URL }}
        TREECREATE_MAIL_PASS: ${{ secrets.TREECREATE_MAIL_PASS }}

    - name: Upload packaged jar
      uses: actions/upload-artifact@v2
      with:
        name: project.jar
        path: target/*.jar
        
  Run_Functional_Tests:
    runs-on: ubuntu-latest
    needs: Package_and_Test
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Google Chrome
      run: |
        chmod +x ./scripts/installChrome.sh
         ./scripts/installChrome.sh

    - name: Download package.jar artifact
      uses: actions/download-artifact@v2
      with:
        name: project.jar
      
    - name: Convert the jar to a runnable version
      run: mv *.jar project.jar
             
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Run the Webserver
      run: java -jar project.jar &
      env:
        TREECREATE_JDBC_URL: ${{ secrets.TREECREATE_JDBC_URL }}
        TREECREATE_MAIL_PASS: ${{ secrets.TREECREATE_MAIL_PASS }}
    
    - name: Wait 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
     
    - name: Run Functional tests
      run: mvn --no-transfer-progress -Dtest=dev.hotdeals.treecreate.functional_tests.** test 
